---
title: "Mean of what?"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

```{r prep}
library(tidyverse)
rm(list=ls())
```


```{r data}

ind <- read_csv("data/pheno/GRSM/GRSM_individual.csv") 
# gcc = ind$g_mean[1]/(sum(ind$g_mean[1]+ind$r_mean[1]+ind$b_mean[1]))

targets <- read_csv("data/pheno/GRSM/GRSM_gccTargets.csv") %>% 
  filter(!is.na(gcc_90))

```

So where does gcc_90 come from in the daily df?
```{r find_gcc90}

ind_10 <- ind %>% 
  filter(solar_elev>10)

midday_gcc <- ind %>%  
  group_by(date) %>% 
  summarize(#meangcc = mean(gcc,na.rm=T),
            # SE1_gcc_90 = as.numeric(quantile(gcc[solar_elev>1],probs=0.9,na.rm=T)),
            SE10_gcc_90 = round(as.numeric(quantile(gcc[solar_elev>10],probs=0.9,na.rm=T)),5),
            SE20_gcc_90 = as.numeric(quantile(gcc[solar_elev>20],probs=0.9,na.rm=T)),
            SE30_gcc_90 = as.numeric(quantile(gcc[solar_elev>30],probs=0.9,na.rm=T)))

midday_gcc <- merge(midday_gcc,targets, by.x='date',by.y='time')
colnames(midday_gcc)[6]<-'target_gcc_90'
midday_gcc$equal = midday_gcc$SE10_gcc_90==midday_gcc$target_gcc_90

```

